########################################
# 由于 GitHub API 限制，最多可以设置 60 个
########################################

links:
  ######## Stellar ########
  # Dalamud TC
  - https://api.github.com/repos/yanmucorp/Dalamud/releases/latest
